### ISSUE TITLE
Use childprocess.fork() instead of cluster

### ISSUE THREAD

**Issue by montogeek** [ericclemmons/start-server-webpack-plugin#12]
I am getting title error after adding `webpack-hot-middleware` and `webpack-dev-middleware` to the server as shown here: https://github.com/gaearon/react-hot-boilerplate/blob/master/server.js
```
Listening at http://localhost:8080
/Users/montogeek/project/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:64
      _cluster2.default.setupMaster({ exec: existsAt });
                        ^

TypeError: _cluster2.default.setupMaster is not a function
    at StartServerPlugin.startServer (/Users/montogeek/project/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:64:25)
    at StartServerPlugin.afterEmit (/Users/montogeek/project/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:36:12)
    at Compiler.applyPluginsAsyncSeries1 (/Users/montogeek/project/node_modules/tapable/lib/Tapable.js:158:13)
    at Compiler.afterEmit (/Users/montogeek/project/node_modules/webpack/lib/Compiler.js:352:8)
    at Compiler.<anonymous> (/Users/montogeek/project/node_modules/webpack/lib/Compiler.js:347:14)
    at /Users/montogeek/project/node_modules/async/dist/async.js:360:16
    at iteratorCallback (/Users/montogeek/project/node_modules/async/dist/async.js:936:13)
    at /Users/montogeek/project/node_modules/async/dist/async.js:844:16
    at MemoryFileSystem.writeFile (/Users/montogeek/project/node_modules/memory-fs/lib/MemoryFileSystem.js:328:9)
    at Compiler.writeOut (/Users/montogeek/project/node_modules/webpack/lib/Compiler.js:341:27)
```

webpack config:
```
{
  entry: ["webpack/hot/poll?1000", "babel-polyfill", "./server/index"],
  watch: true,
  target: "node",
  externals: [nodeExternals({ whitelist: ["webpack/hot/poll?1000"] })],
  module: {
    rules: [
      { test: /\.js?$/, use: "babel-loader", exclude: /node_modules/ },
      {
        test: /\.css$/,
        use: ExtractTextPlugin.extract({
          fallback: "style-loader",
          use: "css-loader"
        })
      },
      {
        test: /\.svg$/,
        use: "raw-loader"
      },
      {
        test: /\.(png|jpg|gif|eot|ttf|woff|woff2)$/,
        loader: "url-loader",
        options: {
          limit: 10000
        }
      }
    ]
  },
  plugins: [
    new ExtractTextPlugin("styles.css"),
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NamedModulesPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new StartServerPlugin("server.js")
  ],
  output: {
    path: path.join(__dirname, ".build"),
    filename: "server.js",
    publicPath: "/"
  }
};
```

Before adding that code, it worked. Maybe a compatibility issue?

**Comment by montogeek** [comment]
This a log from `cluster` when removing webpack stuff:
```
{ default:
   EventEmitter {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     isWorker: false,
     isMaster: true,
     Worker: { [Function: Worker] super_: [Object] },
     workers: {},
     settings: {},
     SCHED_NONE: 1,
     SCHED_RR: 2,
     schedulingPolicy: 2,
     setupMaster: [Function],
     fork: [Function],
     disconnect: [Function] } }
```

After adding webpack stuff:
```
{ default:
   EventEmitter {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     isWorker: true,
     isMaster: false,
     worker:
      Worker {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        exitedAfterDisconnect: undefined,
        suicide: [Getter/Setter],
        state: 'listening',
        id: 1,
        process: [Object] },
     Worker: { [Function: Worker] super_: [Object] },
     _setupWorker: [Function],
     _getServer: [Function] } }
```

**Comment by wmertens** [comment]
strange, so `cluster` thinks it's running as a worker? Very odd…

**Comment by remimarsal** [comment]
@montogeek running into the exact same error using `webpack-hot-middleware` and `webpack-dev-middleware`... Did you find a way or did you drop the plugin altogether ?

**Comment by montogeek** [comment]
@remimarsal Drop it

**Comment by remimarsal** [comment]
@montogeek Ok thank you! Thanks for really fast answer :D

**Comment by wmertens** [comment]
Actually, this is probably because start-server-webpack-plugin runs the script using cluster, see https://github.com/ericclemmons/start-server-webpack-plugin/blob/adbd081eb0b857ddac64540fdbb3edc90f57d54d/src/StartServerPlugin.js#L59-L66

I was thinking that perhaps this plugin should just eval the code in-process. That would also make hot updates faster, and would allow using the in-memory filesystem. Not sure if that will break stuff via webpack's global variables though.

**Comment by wmertens** [comment]
I think using `cluster` in the plugin is actually not a great idea, just forking and restarting would be better. So this issue is about changing the call to cluster to a call to fork.

**Comment by wmertens** [comment]
Should be fixed in `start-server-webpack-plugin@beta`
