### ISSUE TITLE
webpack 4 bug TypeError: Cannot read property 'existsAt' of undefined

### ISSUE THREAD

**Issue by sibelius** [ericclemmons/start-server-webpack-plugin#33]
```
/Users/sibelius/Dev/entria/app/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:120
    const existsAt = compilation.assets[name].existsAt;
                                              ^

TypeError: Cannot read property 'existsAt' of undefined
    at StartServerPlugin.startServer (/Users/sibelius/Dev/entria/app/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:120:47)
    at StartServerPlugin.afterEmit (/Users/sibelius/Dev/entria/app/node_modules/start-server-webpack-plugin/dist/StartServerPlugin.js:90:10)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/sibelius/Dev/entria/app/packages/main/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:14:1)
    at AsyncSeriesHook.lazyCompileHook (/Users/sibelius/Dev/entria/app/packages/main/node_modules/tapable/lib/Hook.js:154:20)
    at asyncLib.forEach.err (/Users/sibelius/Dev/entria/app/packages/main/node_modules/webpack/lib/Compiler.js:354:27)
    at /Users/sibelius/Dev/entria/app/packages/main/node_modules/neo-async/async.js:2825:7
    at done (/Users/sibelius/Dev/entria/app/packages/main/node_modules/neo-async/async.js:2861:11)
    at /Users/sibelius/Dev/entria/app/packages/main/node_modules/neo-async/async.js:2813:7
    at /Users/sibelius/Dev/entria/app/packages/main/node_modules/graceful-fs/graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:141:20)
```

**Comment by wmertens** [comment]
Can you try the @beta version?

**Comment by Magneticmagnum** [comment]
Whats your configuration look like?

**Comment by madebyherzblut** [comment]
In case anyone runs into the same issue: Check that your `output.filename` in your webpack config matches the `name` in your StartServerPlugin config.
